In [1]:
import pandas as pd
import numpy as np

In [2]:
# Set random seed for reproducibility
np.random.seed(42)

In [3]:
# Define the number of samples
num_samples = 100

In [4]:
# Generate synthetic data
data = {
    'area': np.random.randint(500, 2000, size=num_samples),  # Area in square feet
    'number_of_bedrooms': np.random.randint(1, 5, size=num_samples),  # Number of bedrooms (1 to 4)
    'age_of_property': np.random.randint(0, 30, size=num_samples),  # Age of property in years
    'location_rating': np.random.uniform(1, 10, size=num_samples)  # Location rating (1 to 10)
}

In [5]:
# Create a DataFrame
df = pd.DataFrame(data)

In [6]:
# Define a simple linear relationship for flat prices
# Flat price = (area * 100) + (number_of_bedrooms * 50000) - (age_of_property * 2000) + (location_rating * 10000)
df['flat_price'] = (df['area'] * 100) + (df['number_of_bedrooms'] * 50000) - (df['age_of_property'] * 2000) + (df['location_rating'] * 10000)

In [7]:
# Display the first few rows of the DataFrame
df.head()

   area  number_of_bedrooms  age_of_property  location_rating     flat_price
0  1626                   4                5         6.318036  415780.364887
1  1959                   1               27         7.098079  262880.792566
2  1360                   1               27         1.149290  143492.904604
3  1794                   1               11         5.608838  263488.375247
4  1630                   3               11         3.038462  321384.619768

In [8]:
df

    area  number_of_bedrooms  age_of_property  location_rating     flat_price
0   1626                   4                5         6.318036  415780.364887
1   1959                   1               27         7.098079  262880.792566
2   1360                   1               27         1.149290  143492.904604
3   1794                   1               11         5.608838  263488.375247
4   1630                   3               11         3.038462  321384.619768
..   ...                 ...              ...              ...            ...
95  1576                   2               26         8.896358  294563.576474
96  1291                   1                5         7.666918  245769.175598
97   716                   2               15         7.273142  214331.416690
98  1263                   1               28         7.322357  193523.567559
99   687                   1                2         4.235420  157054.203610

[100 rows x 5 columns]

In [9]:
# Import necessary libraries for linear regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
# Select features and target variable
X = df[['area']]  # Feature: area
y = df['flat_price']  # Target: flat_price

In [11]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Create a Linear Regression model
model = LinearRegression()

In [13]:
# Fit the model on the training data
model.fit(X_train, y_train)

LinearRegression()

In [14]:
# Make predictions on the test set
y_pred = model.predict(X_test)

In [15]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [16]:
# Display the results
print("Mean Squared Error:", mse)
print("R^2 Score:", r2)

Mean Squared Error: 3112422071.842484
R^2 Score: 0.34185607460852896

In [17]:
# Display coefficients
print("Coefficient for area:", model.coef_[0])
print("Intercept:", model.intercept_)

Coefficient for area: 117.15996118984593
Intercept: 125847.16752317295